{% set name = "atuin" %}
{% set version = "17.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/atuinsh/atuin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5bad59af24317adfa1d56fce39e231c85836fb91ac3d468830f9bb0884b320ca

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - sysroot_{{ target_platform }} =2.17  # [linux]

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/atuinsh/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Improved shell history for zsh and bash
  dev_url: https://github.com/atuinsh/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
