{% set name = "atuin" %}
{% set version = "18.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/atuinsh/atuin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d05d978d1f1b6a633ac24a9ac9bde3b1dfb7416165b053ef54240fff898aded3

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - protobuf

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/atuinsh/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Improved shell history for zsh and bash
  dev_url: https://github.com/atuinsh/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
