{% set name = "atuin" %}
{% set version = "17.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/atuinsh/atuin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d82c7f4b0b3c04eb6ff1b26b1c4d5219622e1266ced9b48addf7976d2d90bd9a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - sysroot_{{ target_platform }} =2.17  # [linux]

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/atuinsh/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Improved shell history for zsh and bash
  dev_url: https://github.com/atuinsh/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
