{% set name = "atuin" %}
{% set version = "18.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/atuinsh/atuin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 17712bed6528a7f82cc1dffd56b7effe28270ee2f99247908d7a6adff9474338

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - sysroot_{{ target_platform }} =2.17  # [linux]
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/atuinsh/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Improved shell history for zsh and bash
  dev_url: https://github.com/atuinsh/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
