{% set name = "atuin" %}
{% set version = "17.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ellie/atuin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b03d3a1597ba2bbd784612e730419c2cdc099311adf48518bd9c00d2799199f6

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - rust
    - sysroot_linux-64 =2.17  # [linux]
  host:
    - libsodium
  run:
    - libsodium

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/ellie/{{ name }}
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Improved shell history for zsh and bash
  dev_url: https://github.com/ellie/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
