context:
  version: "18.19.0"

package:
  name: atuin
  version: ${{ version }}

source:
  url: https://github.com/atuinsh/atuin/archive/refs/tags/v${{ version }}.tar.gz
  sha256: fdb8268cdd5b13105db79e821f06c1c6624e0c5aee46befb0491e39af42fd4e6

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - libprotobuf
  host:
    - openssl

tests:
  - script:
      - atuin --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Improved shell history for zsh and bash
  homepage: https://github.com/atuinsh/atuin
  repository: https://github.com/atuinsh/atuin

extra:
  recipe-maintainers:
    - danielnachun
