context:
  version: "18.15.0"

package:
  name: atuin
  version: ${{ version }}

source:
  url: https://github.com/atuinsh/atuin/archive/refs/tags/v${{ version }}.tar.gz
  sha256: f381707678ee60497988be1c4f948c10c9ee092a79952e7129575f5d5884f44c

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - libprotobuf

tests:
  - script:
      - atuin --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Improved shell history for zsh and bash
  homepage: https://github.com/atuinsh/atuin
  repository: https://github.com/atuinsh/atuin

extra:
  recipe-maintainers:
    - danielnachun
