context:
  version: "18.12.1"

package:
  name: atuin
  version: ${{ version }}

source:
  url: https://github.com/atuinsh/atuin/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 8643a7df1e366e9ad3134514b9bcaf4d6440accb13c64340ec9ec1923d58eb6e

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - libprotobuf

tests:
  - script:
      - atuin --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Improved shell history for zsh and bash
  homepage: https://github.com/atuinsh/atuin
  repository: https://github.com/atuinsh/atuin

extra:
  recipe-maintainers:
    - danielnachun
