context:
  version: "18.5.0"

package:
  name: atuin
  version: ${{ version }}

source:
  url: https://github.com/atuinsh/atuin/archive/refs/tags/v${{ version }}.tar.gz
  sha256: f3744e8dfee2c7089ac140cb8aafe01e5d77a2299097a2cc0a42db26d127340a

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - libprotobuf

tests:
  - script:
      - atuin --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Improved shell history for zsh and bash
  homepage: https://github.com/atuinsh/atuin
  repository: https://github.com/atuinsh/atuin

extra:
  recipe-maintainers:
    - danielnachun
