context:
  version: "18.8.0"

package:
  name: atuin
  version: ${{ version }}

source:
  url: https://github.com/atuinsh/atuin/archive/refs/tags/v${{ version }}.tar.gz
  sha256: c6463068b4d07cc2543107e293a27d0356783ce7c5f316b64f18e3ca7014430c

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - libprotobuf

tests:
  - script:
      - atuin --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Improved shell history for zsh and bash
  homepage: https://github.com/atuinsh/atuin
  repository: https://github.com/atuinsh/atuin

extra:
  recipe-maintainers:
    - danielnachun
